export const postListDummy = [
    {
        post_nm: 1,
        cover_photo: "/images/dummy/img8.png",
        post_title: "테스트 제목입니다. 제목이 길어지면 어떻게 될까요?",
        explanation: "지난 과거를 돌아보며 내가 공부하면서 좋았던 방법들과 최악의 방법들을 공유하였습니다. 이 글이 당신의 개발 인생 앞날에 좋은 영향력을 끼쳤으면 좋겠습니다. 😃",
        upload_date: "2023년 10월 3일",
        nickname: "dbehddn",
        profile_photo: "/images/dummy/img2.png",
        like_nm: "32",
        reply_nm: "2",
    },
    {
        post_nm: 2,
        cover_photo: "/images/dummy/img2.png",
        post_title: "혼자서 개발하는 사이트는 어떻게 만들어야 할까? 소프트콘 뷰어쉽 제작기 (2)",
        explanation: "소프트콘 뷰어쉽은 아프리카, 트위치에서 방송중인 크리에이터들의 정보를 실시간으로 수집하여 해당 크리에이터의 데이터 및 순위를 보여주는 뷰어쉽 어플리케이션입니다.",
        upload_date: "2023년 9월 29일",
        nickname: "qkrdlsln",
        profile_photo: "/images/dummy/img2.png",
        like_nm: "2",
        reply_nm: "12",
    },
    {
        post_nm: 3,
        cover_photo: "/images/dummy/img4.png",
        post_title: "테스트 제목입니다. 제목이 길어지면 어떻게 될까요?",
        explanation: "이 글이 당신의 개발 인생 앞날에 좋은 영향력을 끼쳤으면 좋겠습니다.",
        upload_date: "2023년 8월 2일",
        nickname: "dlwotmd",
        profile_photo: "/images/dummy/img2.png",
        like_nm: "70",
        reply_nm: "12",
    },
    {
        post_nm: 4,
        cover_photo: "/images/dummy/img3.png",
        post_title: "테스트 제목입니다. 제목이 길어지면 어떻게 될까요?",
        explanation: "이 글이 당신의 개발 인생 앞날에 좋은 영향력을 끼쳤으면 좋겠습니다.",
        upload_date: "2023년 5월 12일",
        nickname: "woodie",
        profile_photo: "/images/dummy/img2.png",
        like_nm: "100",
        reply_nm: "50",
    },
    {
        post_nm: 5,
        cover_photo: "/images/dummy/img5.png",
        post_title: "딥링크 실전에서 잘 사용하는 방법",
        explanation: "모바일 웹 서비스에서 다른 앱을 열어야 하는 경우가 있습니다. 이번 포스트에서는 딥링크에 대해서 알아보고 커스텀 URL 스킴을 중심으로 특정 외부 앱을 실행하는 방법을 알아볼게요.",
        upload_date: "2023년 2월 4일",
        nickname: "seung2",
        profile_photo: "/images/dummy/img2.png",
        like_nm: "120",
        reply_nm: "780",
    }
]
