import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/styles/globals.css";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Maestlog',
  description: 'Generated by Maestlog',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="body_all">
          <div className="inner">
            <div className="container">
              <Header />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
